language: erlang

env:
  - LUA=""
  - LUA="luajit"

branches:
  only:
    - master
    - develop

install:
  - sudo apt-get install luajit
  - sudo apt-get install luarocks
  - sudo luarocks install luafilesystem
  - sudo luarocks install busted

script: "busted spec"

notifications:

  recipients:
    - lucas@tuirtleswamp.com
  email:
    on_success: change
    on_failure: always